### ISSUE TITLE
resarting activity causes ANR

### ISSUE THREAD

**Issue by pscholl** [pscholl/cmotion#25]

**Comment by pscholl** [comment]
also drops the settings

**Comment by paulgavrikov** [comment]
settings in terms of checked sensors? persisting happens onPause, I'll introduce a check listener that persists on each check

**Comment by paulgavrikov** [comment]
> E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                           Process: es.uni_freiburg.de.cmotion, PID: 5109
>                                                                           java.lang.RuntimeException: Unable to destroy activity {es.uni_freiburg.de.cmotion/es.uni_freiburg.de.cmotion.CMotionActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.uni_freiburg.es.sensorrecordingtool.autodiscovery.AutoDiscovery$1@6879233
>                                                                               at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
>                                                                               at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
>                                                                               at android.app.ActivityThread.-wrap5(ActivityThread.java)
>                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
>                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                               at android.os.Looper.loop(Looper.java:148)
>                                                                               at android.app.ActivityThread.main(ActivityThread.java:5422)
>                                                                               at java.lang.reflect.Method.invoke(Native Method)
>                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>                                                                            Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.uni_freiburg.es.sensorrecordingtool.autodiscovery.AutoDiscovery$1@6879233
>                                                                               at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:780)
>                                                                               at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1195)
>                                                                               at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:576)
>                                                                               at de.uni_freiburg.es.sensorrecordingtool.autodiscovery.AutoDiscovery.close(AutoDiscovery.java:104)
>                                                                               at es.uni_freiburg.de.cmotion.AutoDiscoveryWrapper.close(AutoDiscoveryWrapper.java:83)
>                                                                               at es.uni_freiburg.de.cmotion.CMotionActivity.onDestroy(CMotionActivity.java:145)
>                                                                               at android.app.Activity.performDestroy(Activity.java:6422)
>                                                                               at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
>                                                                               at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
>                                                                               at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849) 
>                                                                               at android.app.ActivityThread.-wrap5(ActivityThread.java) 
>                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
>                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                               at android.os.Looper.loop(Looper.java:148) 
>                                                                               at android.app.ActivityThread.main(ActivityThread.java:5422) 
>                                                                               at java.lang.reflect.Method.invoke(Native Method) 
>                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by paulgavrikov** [comment]
only caused by Instant Run
