### ISSUE TITLE
define a timeout when recording cannot be started

### ISSUE THREAD

**Issue by pscholl** [pscholl/cmotion#26]

**Comment by pscholl** [comment]
add possibility to stop steadying

**Comment by paulgavrikov** [comment]
steadying stop is implemented in todays commit

**Comment by paulgavrikov** [comment]
timeout might be critical, think about this:
Smartphone is master and ready
Wear is slave and waiting for sensors
After a while the phone gets a timeout and sends steady => Wear countdownlatch is decremented 
Now the phone is already recording for some seconds and the wear is finally ready. The latch is decremented, thus recording immediately starts.

What shall we do in this case?
a) stop recording globally?
b) let only the phone record? (e.g. Countdownlatch can be only decremented, when the SRT is ready)
c) attempt some recovery protocol?
