### ISSUE TITLE
recording bar in App can get stuck in recording state

### ISSUE THREAD

**Issue by pscholl** [pscholl/cmotion#36]
even though recording was stopped

**Comment by paulgavrikov** [comment]
Isnt that related to the flush issue? Or was that some UI bug?

**Comment by pscholl** [comment]
Don't know, was no ANR though (have you pushed those changes already?).

On Mon, Mar 27, 2017 at 03:04:42AM -0700, Paul Gavrikov wrote:
> Isnt that related to the flush issue? Or was that some UI bug?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pscholl/cmotion/issues/36#issuecomment-289409742

-- 
Eingebettete Systeme - Universität Freiburg
https://es.informatik.uni-freiburg.de
Tel: +49 761 203-98-587

**Comment by pscholl** [comment]
merged away :)
